call c:\xml.bat
cd T01
call xml2txt -v T01 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T02
call xml2txt -v T02 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T03
call xml2txt -v T03 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T04
call xml2txt -v T04 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T05
call xml2txt -v T05 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T06
call xml2txt -v T06 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T07
call xml2txt -v T07 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T08
call xml2txt -v T08 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T09
call xml2txt -v T09 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T10
call xml2txt -v T10 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T11
call xml2txt -v T11 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T12
call xml2txt -v T12 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T13
call xml2txt -v T13 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T14
call xml2txt -v T14 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T15
call xml2txt -v T15 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T16
call xml2txt -v T16 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T17
call xml2txt -v T17 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T18
call xml2txt -v T18 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T19
call xml2txt -v T19 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T20
call xml2txt -v T20 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T21
call xml2txt -v T21 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T22
call xml2txt -v T22 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T23
call xml2txt -v T23 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T24
call xml2txt -v T24 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T25
call xml2txt -v T25 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T26
call xml2txt -v T26 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T27
call xml2txt -v T27 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T28
call xml2txt -v T28 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T29
call xml2txt -v T29 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T30
call xml2txt -v T30 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T31
call xml2txt -v T31 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T32
call xml2txt -v T32 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T33
call xml2txt -v T33 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T34
call xml2txt -v T34 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T35
call xml2txt -v T35 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T36
call xml2txt -v T36 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T37
call xml2txt -v T37 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T38
call xml2txt -v T38 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T39
call xml2txt -v T39 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T40
call xml2txt -v T40 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T41
call xml2txt -v T41 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T42
call xml2txt -v T42 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T43
call xml2txt -v T43 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T44
call xml2txt -v T44 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T45
call xml2txt -v T45 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T46
call xml2txt -v T46 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T47
call xml2txt -v T47 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T48
call xml2txt -v T48 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T49
call xml2txt -v T49 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T50
call xml2txt -v T50 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T51
call xml2txt -v T51 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T52
call xml2txt -v T52 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T53
call xml2txt -v T53 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T54
call xml2txt -v T54 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T55
call xml2txt -v T55 -u -h -k -z -x 2
cd c:\cbwork\xml
cd T85
call xml2txt -v T85 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X01
call xml2txt -v X01 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X02
call xml2txt -v X02 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X03
call xml2txt -v X03 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X04
call xml2txt -v X04 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X05
call xml2txt -v X05 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X07
call xml2txt -v X07 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X08
call xml2txt -v X08 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X09
call xml2txt -v X09 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X10
call xml2txt -v X10 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X11
call xml2txt -v X11 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X12
call xml2txt -v X12 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X13
call xml2txt -v X13 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X14
call xml2txt -v X14 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X15
call xml2txt -v X15 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X16
call xml2txt -v X16 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X17
call xml2txt -v X17 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X18
call xml2txt -v X18 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X19
call xml2txt -v X19 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X20
call xml2txt -v X20 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X21
call xml2txt -v X21 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X22
call xml2txt -v X22 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X23
call xml2txt -v X23 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X24
call xml2txt -v X24 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X25
call xml2txt -v X25 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X26
call xml2txt -v X26 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X27
call xml2txt -v X27 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X28
call xml2txt -v X28 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X29
call xml2txt -v X29 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X30
call xml2txt -v X30 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X31
call xml2txt -v X31 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X32
call xml2txt -v X32 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X33
call xml2txt -v X33 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X34
call xml2txt -v X34 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X35
call xml2txt -v X35 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X36
call xml2txt -v X36 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X37
call xml2txt -v X37 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X38
call xml2txt -v X38 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X39
call xml2txt -v X39 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X40
call xml2txt -v X40 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X41
call xml2txt -v X41 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X42
call xml2txt -v X42 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X43
call xml2txt -v X43 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X44
call xml2txt -v X44 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X45
call xml2txt -v X45 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X46
call xml2txt -v X46 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X47
call xml2txt -v X47 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X48
call xml2txt -v X48 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X49
call xml2txt -v X49 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X50
call xml2txt -v X50 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X51
call xml2txt -v X51 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X53
call xml2txt -v X53 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X54
call xml2txt -v X54 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X55
call xml2txt -v X55 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X56
call xml2txt -v X56 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X57
call xml2txt -v X57 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X58
call xml2txt -v X58 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X59
call xml2txt -v X59 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X60
call xml2txt -v X60 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X61
call xml2txt -v X61 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X62
call xml2txt -v X62 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X63
call xml2txt -v X63 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X64
call xml2txt -v X64 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X65
call xml2txt -v X65 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X66
call xml2txt -v X66 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X67
call xml2txt -v X67 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X68
call xml2txt -v X68 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X69
call xml2txt -v X69 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X70
call xml2txt -v X70 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X71
call xml2txt -v X71 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X72
call xml2txt -v X72 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X73
call xml2txt -v X73 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X74
call xml2txt -v X74 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X75
call xml2txt -v X75 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X76
call xml2txt -v X76 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X77
call xml2txt -v X77 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X78
call xml2txt -v X78 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X79
call xml2txt -v X79 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X80
call xml2txt -v X80 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X81
call xml2txt -v X81 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X82
call xml2txt -v X82 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X83
call xml2txt -v X83 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X84
call xml2txt -v X84 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X85
call xml2txt -v X85 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X86
call xml2txt -v X86 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X87
call xml2txt -v X87 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X88
call xml2txt -v X88 -u -h -k -z -x 2
cd c:\cbwork\xml
